[Train]
State = Test
;State = Train / Finetune / Test
batch_size = 8
test_rate = 0.2
GPU = 0
epochs = 500
save_every = 10

;lr = 0.0001
lr = 0.0003
seed = 0

emb_dim = 128
pq_M = 8
pq_K = 32
pq_softmax_temp = 1.0
pq_quant_method = softmax
pq_init_neg_curvs = 1.0
pq_clip_r = 1.0
pq_use_alpha = False

Spatial_Area_x1 = 1
Spatial_Area_x2 = 6
Time_Area_n = 5

mask_ratio = 0.2
recon_weight = 1
cluster_weight = 1

margin_M = 1
w_min = 0.2
w_max = 0.8



[Data]

sfrq = 500
time_window_length = 10
time_window_overlap = 0.75

patch_length = 1

target_domain = 4584
